// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: ruijie-json.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonDeviceMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProducerName string `protobuf:"bytes,1,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	DeviceName   string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceModel  string `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
}

func (x *JsonDeviceMsg) Reset() {
	*x = JsonDeviceMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ruijie_json_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonDeviceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonDeviceMsg) ProtoMessage() {}

func (x *JsonDeviceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ruijie_json_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonDeviceMsg.ProtoReflect.Descriptor instead.
func (*JsonDeviceMsg) Descriptor() ([]byte, []int) {
	return file_ruijie_json_proto_rawDescGZIP(), []int{0}
}

func (x *JsonDeviceMsg) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *JsonDeviceMsg) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *JsonDeviceMsg) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

// 厂商名称 // 设备名称 // 设备型号
type JsonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceInfo *JsonDeviceMsg `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	JsonEvent  uint32         `protobuf:"varint,2,opt,name=json_event,json=jsonEvent,proto3" json:"json_event,omitempty"`
	JsonString string         `protobuf:"bytes,3,opt,name=json_string,json=jsonString,proto3" json:"json_string,omitempty"`
	// Deprecated: Do not use.
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Deprecated: Do not use.
	SensorPath string `protobuf:"bytes,5,opt,name=sensor_path,json=sensorPath,proto3" json:"sensor_path,omitempty"`
}

func (x *JsonRequest) Reset() {
	*x = JsonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ruijie_json_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRequest) ProtoMessage() {}

func (x *JsonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ruijie_json_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRequest.ProtoReflect.Descriptor instead.
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return file_ruijie_json_proto_rawDescGZIP(), []int{1}
}

func (x *JsonRequest) GetDeviceInfo() *JsonDeviceMsg {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *JsonRequest) GetJsonEvent() uint32 {
	if x != nil {
		return x.JsonEvent
	}
	return 0
}

func (x *JsonRequest) GetJsonString() string {
	if x != nil {
		return x.JsonString
	}
	return ""
}

// Deprecated: Do not use.
func (x *JsonRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Deprecated: Do not use.
func (x *JsonRequest) GetSensorPath() string {
	if x != nil {
		return x.SensorPath
	}
	return ""
}

type JsonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"zigzag32,1,opt,name=ret,proto3" json:"ret,omitempty"` // 处理是否成功，成功为 1，失败为 0
}

func (x *JsonReply) Reset() {
	*x = JsonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ruijie_json_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonReply) ProtoMessage() {}

func (x *JsonReply) ProtoReflect() protoreflect.Message {
	mi := &file_ruijie_json_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonReply.ProtoReflect.Descriptor instead.
func (*JsonReply) Descriptor() ([]byte, []int) {
	return file_ruijie_json_proto_rawDescGZIP(), []int{2}
}

func (x *JsonReply) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_ruijie_json_proto protoreflect.FileDescriptor

var file_ruijie_json_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x75, 0x69, 0x6a, 0x69, 0x65, 0x2d, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x75, 0x69, 0x6a, 0x69, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x22, 0x78, 0x0a, 0x0d, 0x4a, 0x73, 0x6f, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x73,
	0x67, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xd1, 0x01, 0x0a, 0x0b, 0x4a,
	0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x72, 0x75, 0x69, 0x6a, 0x69, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x4a, 0x73,
	0x6f, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6a, 0x73, 0x6f,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6a, 0x73, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x18, 0x01, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x23, 0x0a, 0x0b, 0x73, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x22, 0x1d,
	0x0a, 0x09, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x72, 0x65, 0x74, 0x32, 0x46, 0x0a,
	0x04, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x6e,
	0x64, 0x12, 0x18, 0x2e, 0x72, 0x75, 0x69, 0x6a, 0x69, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e,
	0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x75,
	0x69, 0x6a, 0x69, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ruijie_json_proto_rawDescOnce sync.Once
	file_ruijie_json_proto_rawDescData = file_ruijie_json_proto_rawDesc
)

func file_ruijie_json_proto_rawDescGZIP() []byte {
	file_ruijie_json_proto_rawDescOnce.Do(func() {
		file_ruijie_json_proto_rawDescData = protoimpl.X.CompressGZIP(file_ruijie_json_proto_rawDescData)
	})
	return file_ruijie_json_proto_rawDescData
}

var file_ruijie_json_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ruijie_json_proto_goTypes = []interface{}{
	(*JsonDeviceMsg)(nil), // 0: ruijie_json.JsonDeviceMsg
	(*JsonRequest)(nil),   // 1: ruijie_json.JsonRequest
	(*JsonReply)(nil),     // 2: ruijie_json.JsonReply
}
var file_ruijie_json_proto_depIdxs = []int32{
	0, // 0: ruijie_json.JsonRequest.device_info:type_name -> ruijie_json.JsonDeviceMsg
	1, // 1: ruijie_json.Json.JsonSend:input_type -> ruijie_json.JsonRequest
	2, // 2: ruijie_json.Json.JsonSend:output_type -> ruijie_json.JsonReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ruijie_json_proto_init() }
func file_ruijie_json_proto_init() {
	if File_ruijie_json_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ruijie_json_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonDeviceMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ruijie_json_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ruijie_json_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ruijie_json_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruijie_json_proto_goTypes,
		DependencyIndexes: file_ruijie_json_proto_depIdxs,
		MessageInfos:      file_ruijie_json_proto_msgTypes,
	}.Build()
	File_ruijie_json_proto = out.File
	file_ruijie_json_proto_rawDesc = nil
	file_ruijie_json_proto_goTypes = nil
	file_ruijie_json_proto_depIdxs = nil
}
